### ISSUE TITLE
JVM crashes with appmap-maven-plugin 1.2.1 and `mvn clean test`

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-java#144]
I cloned https://github.com/spring-projects/spring-petclinic and executed `mvn clean test`. For odd reasons this is crashing the JVM.
I've attached the surefire-reports folder, which contains the JVM crash reports.

OS: Linux

```
$ java --version
openjdk 11.0.16.1 2022-08-12
OpenJDK Runtime Environment (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM (build 11.0.16.1+1, mixed mode)
```

Same with Java 18:
```
$ java --version
openjdk 18.0.2 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+0)
OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mode)
```

Repo:
```
$ git remote -v
origin  git@github.com:land-of-apps/spring-petclinic.git (fetch)
origin  git@github.com:land-of-apps/spring-petclinic.git (push)
```

[surefire-reports.zip](https://github.com/applandinc/appmap-java/files/9586471/surefire-reports.zip)

```
-------------------------------------------------------------------------------
Test set: org.springframework.samples.petclinic.owner.OwnerControllerTests
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.638 s <<< FAILURE! - in org.springframework.samples.petclinic.owner.OwnerControllerTests
testProcessUpdateOwnerFormHasErrors  Time elapsed: 0.006 s  <<< ERROR!
org.springframework.web.util.NestedServletException: 
Handler dispatch failed; nested exception is java.lang.VerifyError: Expecting a stackmap frame at branch target 295
Exception Details:
  Location:
    org/springframework/web/method/support/InvocableHandlerMethod.doInvoke([Ljava/lang/Object;)Ljava/lang/Object; @103: goto
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: b801 37b6 013a b801 37b6 013d 9900 22b8
    0000010: 0143 110c 14b6 0147 2a04 bd00 1959 032b
    0000020: b801 4d53 b801 53b8 0137 b601 5657 b801
    0000030: 154d 2ab6 0029 4e2c 1026 0454 2db8 002a
    0000040: 2c10 2704 542d b800 2b9a 000b 2c10 2804
    0000050: 54a7 0019 2c10 2904 542d 2ab6 002c 2bb8
    0000060: 002d 2c10 2a04 54a7 00c0 2d2a b600 2c2b
    0000070: b600 2e2c 102b 0454 a700 af3a 042c 102c
    0000080: 0454 2a2d 2ab6 002c 2bb6 0030 2c10 2d04
    0000090: 5419 04b6 0031 c600 1019 04b6 0031 2c10
    00000a0: 2e04 54a7 000a 1232 2c10 2f04 543a 052c
    00000b0: 1030 0454 bb00 1d59 2a19 052b b600 3319
    00000c0: 04b7 0034 2c10 3104 54bf 3a04 2c10 3204
    00000d0: 5419 04b6 0036 3a05 1905 c100 3799 000e
    00000e0: 1905 c000 372c 1033 0454 bf19 05c1 0038
    00000f0: 9900 0e19 05c0 0038 2c10 3404 54bf 1905
    0000100: c100 7e99 000e 1905 c000 7e2c 1035 0454
    0000110: bfbb 001d 592a 1239 2bb6 0033 1905 b700
    0000120: 342c 1036 0454 bf3a 07b8 0137 b601 3d99
    0000130: 0027 b801 4311 0c13 b601 592a 1907 b801
    0000140: 4d04 bd00 1959 032b b801 4d53 b801 5eb8
    0000150: 0137 b601 5657 b801 37b6 0161 1907 b0  
  Exception Handler Table:
    bci [64, 98] => handler: 123
    bci [106, 115] => handler: 123
    bci [64, 98] => handler: 202
    bci [106, 115] => handler: 202
  Stackmap Table:
    same_frame(@46)
    append_frame(@84,Object[#279],Object[#196])
    same_frame(@106)
    same_locals_1_stack_item_frame(@123,Object[#135])
    append_frame(@166,Object[#135])
    same_locals_1_stack_item_frame(@173,Object[#185])
    full_frame(@202,{Object[#137],Object[#111],Object[#279],Object[#196]},{Object[#138]})
    append_frame(@235,Object[#138],Object[#139])
    same_frame(@254)
    same_frame(@273)
```

**Comment by jansorg** [comment]
@apotterri Here's output of Java 18 with spring-petclinic after updating to the latest Javassist. It's containing more context.
Is the agent somehow modifying the stacks of method calls in a way, which doesn't match with the JVM's expectations?

```
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:43) ~[spring-boot-test-autoconfigure-2.7.3.jar:2.7.3]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138) ~[spring-test-5.3.22.jar:5.3.22]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$8(ClassBasedTestDescriptor.java:363) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:368) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$9(ClassBasedTestDescriptor.java:363) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[na:na]
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[na:na]
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[na:na]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:362) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$instantiateAndPostProcessTestInstance$6(ClassBasedTestDescriptor.java:283) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:282) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:272) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[na:na]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:271) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:102) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:101) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:66) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53) ~[junit-platform-launcher-1.8.2.jar:1.8.2]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71) ~[junit5-rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38) ~[junit-rt.jar:na]
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11) ~[idea_rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235) ~[junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) ~[junit-rt.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is java.lang.VerifyError: Stack map does not match the one at exception handler 151
Exception Details:
  Location:
    jdk/proxy1/$Proxy121.nativeSQL(Ljava/lang/String;)Ljava/lang/String; @151: astore
  Reason:
    Type 'java/lang/Throwable' (current frame, locals[1]) is not assignable to 'java/lang/String' (stack map, locals[1])
  Current Frame:
    bci: @87
    flags: { }
    locals: { 'jdk/proxy1/$Proxy121', 'java/lang/Throwable' }
    stack: { 'com/appland/appmap/process/ExitEarly' }
  Stackmap Frame:
    bci: @151
    flags: { }
    locals: { 'jdk/proxy1/$Proxy121', 'java/lang/String' }
    stack: { 'com/appland/appmap/process/ExitEarly' }
  Bytecode:
    0000000: b801 feb6 0201 b801 fe13 0203 b602 0757
    0000010: b801 feb6 020a 9900 24b8 01fe 1302 03b6
    0000020: 020d 9900 11b8 0213 1103 dbb6 0217 2a2b
    0000030: b802 1cb8 01fe b602 1f57 2ab4 0018 2ab2
    0000040: 006d 04bd 0031 5903 2b53 b900 2004 00c0
    0000050: 003e a700 0ebf 4cbb 0027 592b b700 2abf
    0000060: 4eb8 01fe b602 0a99 0028 b801 fe13 0203
    0000070: b602 0d99 0015 b802 1311 03dc b602 222a
    0000080: 2db8 0228 2bb8 022b b801 feb6 021f 57b8
    0000090: 01fe b602 2e2d b03a 04b8 01fe b602 2e19
    00000a0: 04b6 0234 c000 3eb0 3a05 b801 feb6 020a
    00000b0: 9900 29b8 01fe 1302 03b6 020d 9900 16b8
    00000c0: 0213 1103 ddb6 0222 2a19 05c0 0236 2bb8
    00000d0: 0239 b801 feb6 021f 57b8 01fe b602 2e19
    00000e0: 05bf                                   
  Exception Handler Table:
    bci [58, 85] => handler: 85
    bci [58, 85] => handler: 85
    bci [58, 85] => handler: 85
    bci [58, 85] => handler: 86
    bci [0, 151] => handler: 151
    bci [0, 168] => handler: 168
  Stackmap Table:
    same_frame(@51)
    same_frame(@58)
    same_locals_1_stack_item_frame(@85,Object[#20])
    same_locals_1_stack_item_frame(@86,Object[#20])
    same_locals_1_stack_item_frame(@96,Object[#62])
    append_frame(@136,Top,Object[#62])
    same_frame(@143)
    full_frame(@151,{Object[#2],Object[#62]},{Object[#560]})
    same_locals_1_stack_item_frame(@168,Object[#566])
    full_frame(@210,{Object[#2],Object[#62],Top,Top,Top,Object[#566]},{})
    same_frame(@217)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:132) ~[spring-boot-test-2.7.3.jar:2.7.3]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[spring-test-5.3.22.jar:5.3.22]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-5.3.22.jar:5.3.22]
	... 72 common frames omitted
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 151
Exception Details:
  Location:
    jdk/proxy1/$Proxy121.nativeSQL(Ljava/lang/String;)Ljava/lang/String; @151: astore
  Reason:
    Type 'java/lang/Throwable' (current frame, locals[1]) is not assignable to 'java/lang/String' (stack map, locals[1])
  Current Frame:
    bci: @87
    flags: { }
    locals: { 'jdk/proxy1/$Proxy121', 'java/lang/Throwable' }
    stack: { 'com/appland/appmap/process/ExitEarly' }
  Stackmap Frame:
    bci: @151
    flags: { }
    locals: { 'jdk/proxy1/$Proxy121', 'java/lang/String' }
    stack: { 'com/appland/appmap/process/ExitEarly' }
  Bytecode:
    0000000: b801 feb6 0201 b801 fe13 0203 b602 0757
    0000010: b801 feb6 020a 9900 24b8 01fe 1302 03b6
    0000020: 020d 9900 11b8 0213 1103 dbb6 0217 2a2b
    0000030: b802 1cb8 01fe b602 1f57 2ab4 0018 2ab2
    0000040: 006d 04bd 0031 5903 2b53 b900 2004 00c0
    0000050: 003e a700 0ebf 4cbb 0027 592b b700 2abf
    0000060: 4eb8 01fe b602 0a99 0028 b801 fe13 0203
    0000070: b602 0d99 0015 b802 1311 03dc b602 222a
    0000080: 2db8 0228 2bb8 022b b801 feb6 021f 57b8
    0000090: 01fe b602 2e2d b03a 04b8 01fe b602 2e19
    00000a0: 04b6 0234 c000 3eb0 3a05 b801 feb6 020a
    00000b0: 9900 29b8 01fe 1302 03b6 020d 9900 16b8
    00000c0: 0213 1103 ddb6 0222 2a19 05c0 0236 2bb8
    00000d0: 0239 b801 feb6 021f 57b8 01fe b602 2e19
    00000e0: 05bf                                   
  Exception Handler Table:
    bci [58, 85] => handler: 85
    bci [58, 85] => handler: 85
    bci [58, 85] => handler: 85
    bci [58, 85] => handler: 86
    bci [0, 151] => handler: 151
    bci [0, 168] => handler: 168
  Stackmap Table:
    same_frame(@51)
    same_frame(@58)
    same_locals_1_stack_item_frame(@85,Object[#20])
    same_locals_1_stack_item_frame(@86,Object[#20])
    same_locals_1_stack_item_frame(@96,Object[#62])
    append_frame(@136,Top,Object[#62])
    same_frame(@143)
    full_frame(@151,{Object[#2],Object[#62]},{Object[#560]})
    same_locals_1_stack_item_frame(@168,Object[#566])
    full_frame(@210,{Object[#2],Object[#62],Top,Top,Top,Object[#566]},{})
    same_frame(@217)

	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3405) ~[na:na]
	at java.base/java.lang.Class.getConstructor0(Class.java:3610) ~[na:na]
	at java.base/java.lang.Class.getConstructor(Class.java:2303) ~[na:na]
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.build(Proxy.java:675) ~[na:na]
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:429) ~[na:na]
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[na:na]
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[na:na]
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:427) ~[na:na]
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037) ~[na:na]
	at org.springframework.jdbc.core.JdbcTemplate.createConnectionProxy(JdbcTemplate.java:361) ~[spring-jdbc-5.3.22.jar:5.3.22]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:333) ~[spring-jdbc-5.3.22.jar:5.3.22]
	at org.springframework.boot.jdbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:162) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.jdbc.init.DataSourceScriptDatabaseInitializer.isEmbeddedDatabase(DataSourceScriptDatabaseInitializer.java:70) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.isEnabled(AbstractScriptDatabaseInitializer.java:83) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applyScripts(AbstractScriptDatabaseInitializer.java:106) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.applySchemaScripts(AbstractScriptDatabaseInitializer.java:97) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.initializeDatabase(AbstractScriptDatabaseInitializer.java:75) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.sql.init.AbstractScriptDatabaseInitializer.afterPropertiesSet(AbstractScriptDatabaseInitializer.java:65) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.22.jar:5.3.22]
	... 90 common frames omitted
```

**Comment by apotterri** [comment]
> Is the agent somehow modifying the stacks of method calls in a way, which doesn't match with the JVM's expectations?

That's what javassist seems to be doing, yes.
