### ISSUE TITLE
Getting initializationError while running Tests with AppMap with Gradle

### ISSUE THREAD

**Issue by ram-kushwaha** [getappmap/appmap-java#159]
## appmap.yml

```
# 'name' should generally be the same as the code repo name.
name: PricingService
packages:
- path: com.nuorder.service.pricing
  # exclude: [ com.mycorp.myproject.MyClass#MyMethod ]
- path: org.springframework.web
  shallow: true
  exclude: 
   - org.springframework.web.util
- path: java.util.logging
  methods:
  - class: Logger
    name: log
```

## Command

```
gradlew.bat appmap test
```

### Error Log

```
org.mockito.exceptions.base.MockitoException: 

No tests found in PriceEntityGrpcServiceTest
Is the method annotated with @Test?
Is the method public?

	at app//org.mockito.internal.runners.RunnerFactory.create(RunnerFactory.java:82)
	at app//org.mockito.internal.runners.RunnerFactory.createStrict(RunnerFactory.java:40)
	at app//org.mockito.junit.MockitoJUnitRunner.<init>(MockitoJUnitRunner.java:154)
	at java.base@11.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@11.0.2/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base@11.0.2/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@11.0.2/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at app//org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at app//org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at app//org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at app//org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at app//org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at app//org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at app//org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:78)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.2/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.mockito.internal.runners.util.RunnerProvider.newInstance(RunnerProvider.java:29)
	at org.mockito.internal.runners.RunnerFactory.create(RunnerFactory.java:75)
	... 36 more
Caused by: org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.nuorder.service.pricing.grpc.PriceEntityGrpcServiceTest':
  1. No runnable methods
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:92)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:74)
	at org.mockito.internal.runners.DefaultInternalRunner$1.<init>(DefaultInternalRunner.java:31)
	at org.mockito.internal.runners.DefaultInternalRunner.<init>(DefaultInternalRunner.java:30)
	... 42 more

```

### Test class file (truncated)

```java

@ExtendWith(MockitoExtension.class)
@RunWith(MockitoJUnitRunner.class)
public class PriceEntityGrpcServiceTest {
```

....
....

```java
@Test
  public void testCreate() {
    PriceEntity priceEntity = testEntity();
    CreatePricingEntityRequest request =
        CreatePricingEntityRequest.newBuilder()
            .setEntity(priceEntity)
            .setMerchantId("merchant1")
            .build();
    StreamObserver streamObserver = Mockito.mock(StreamObserver.class);
    service.createPricingEntity(request, streamObserver);
    ArgumentCaptor<PriceEntity> captor = ArgumentCaptor.forClass(PriceEntity.class);
    verify(bigtableRepository).create(captor.capture());
    PriceEntity auditPriceEntity = captor.getValue();
    TestUtils.verifyAuditedPriceEntity(priceEntity, auditPriceEntity, getUser());
    verify(pricingSearchRepository).save(any(TaggedPriceEntity.class));
    ArgumentCaptor<CreatePricingEntityResponse> responseCaptor =
        ArgumentCaptor.forClass(CreatePricingEntityResponse.class);
    verify(streamObserver).onNext(responseCaptor.capture());
    TestUtils.verifyAuditedPriceEntity(
        priceEntity, responseCaptor.getValue().getEntity(), getUser());
    verify(streamObserver).onCompleted();
    verifyNoMoreInteractions(streamObserver);
  }
```

**Comment by apotterri** [comment]
Hi @ram-kushwaha , thanks very much for trying AppMap. Sorry you've run into some trouble.

Can you confirm that the tests run correctly when run as `gradlew.bat test`? If so, then it's likely there's some incompatibility between Mockito and the agent.
