### ISSUE TITLE
Exception `Invalid link across device bounds`

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-java#162]
JetBrains plugin 0.22.0 with Java agent version 1.15.4.
I tried to execute all tests of the latest https://github.com/spring-projects/spring-petclinic with the JetBrains plugin's executor.

The agent seems to attempt to move a file atomicallly, but this is failing because `/tmp` and `/home` are mounted on different devices.  `/tmp` is an in-memory filesystem, which is common on Linux setups.

The german message `Ungültiger Link über Gerätegrenzen hinweg` means `Invalid link across device bounds` (or similar).

```
java.nio.file.AtomicMoveNotSupportedException: /tmp/16025911868108154225.appmap.json -> /home/user/sources/spring-petclinic/target/appmap/junit/org_springframework_samples_petclinic_PetClinicIntegrationTests_testOwnerDetails.appmap.json: Ungültiger Link über Gerätegrenzen hinweg
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:414)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at com.appland.appmap.record.Recording.lambda$moveTo$1(Recording.java:53)
	at com.appland.appmap.record.Recording.lambda$moveTo$0(Recording.java:45)
	at com.appland.appmap.record.Recording.moveTo(Recording.java:65)
	at com.appland.appmap.process.hooks.remoterecording.ServletHooks.stopRecording(ServletHooks.java:144)
	at com.appland.appmap.process.hooks.remoterecording.ServletHooks.stopRecording(ServletHooks.java:129)
	at com.appland.appmap.process.hooks.remoterecording.ServletHooks.junitJupiter(ServletHooks.java:181)
	at org.springframework.samples.petclinic.PetClinicIntegrationTests.testOwnerDetails(PetClinicIntegrationTests.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```

**Comment by apotterri** [comment]
Looking at the code, it attempts to handle the case where an atomic move fails. It's hard to tell whether that code is broken, or if this error message is just informational.

Seems like it would be better if the logging that happens [here](https://github.com/getappmap/appmap-java/blob/02adad7a8706137a137cd9940982143051f44368/agent/src/main/java/com/appland/appmap/record/Recording.java#L70) happened [here](https://github.com/getappmap/appmap-java/blob/02adad7a8706137a137cd9940982143051f44368/agent/src/main/java/com/appland/appmap/record/Recording.java#L79) instead.

**Comment by symwell** [comment]
It's a bug in the code.  Java can't move files across filesystems atomically.

Reproduced with the following program:
```
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.ATOMIC_MOVE;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;

public class ShowAtomicMoveError {

    public static void main(String[] args) {
        Path srcPath = Paths.get("/tmp/some_file");
        Path dstPath = Paths.get("/dev/shm/some_file");
        try {
            Files.move(srcPath, dstPath, REPLACE_EXISTING, ATOMIC_MOVE);
        } catch (IOException e) {
            System.out.println(e);
        }
    }
}
```

With `ATOMIC_MOVE`
```
$ touch /tmp/some_file; javac ShowAtomicMoveError.java && java ShowAtomicMoveError
java.nio.file.AtomicMoveNotSupportedException: /tmp/some_file -> /dev/shm/some_file: Invalid cross-device link
```
Without `ATOMIC_MOVE`
```
$ touch /tmp/some_file; javac ShowAtomicMoveError.java && java ShowAtomicMoveError
```
Also get no error moving within the same filesystem with `ATOMIC_MOVE`.

**Comment by apotterri** [comment]
The code is clearly [trying](https://github.com/getappmap/appmap-java/blob/02adad7a8706137a137cd9940982143051f44368/agent/src/main/java/com/appland/appmap/record/Recording.java#L52) to handle this. It first tries with `ATOMIC_MOVE`. Then, if that fails, it tries without `ATOMIC_MOVE`. Finally, it will try to copy the file.
