### ISSUE TITLE
Error in server using eureka discovery in a spring boot app

### ISSUE THREAD

**Issue by tokazio** [getappmap/appmap-java#175]
I'm trying appmap for the first time.

No problem with a remote recording of the http endpoints.

But I have this error when using the javaagent on my service.

```
2023-04-20 17:08:30.343  INFO [prometheus,,] 44579 --- [freshExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://localhost:8102/eureka/}, exception=java.lang.NullPointerException stacktrace=com.sun.jersey.api.client.ClientHandlerException: java.lang.NullPointerException
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:196)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplications(AbstractJerseyEurekaHttpClient.java:167)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:121)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:80)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1101)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:1014)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1531)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1498)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at com.appland.appmap.process.hooks.HttpClientRequest.execute(HttpClientRequest.java:27)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
```

**Comment by apotterri** [comment]
Hi @tokazio. Thanks for trying AppMap, and thanks very much for reporting this issue.

Do you have, or do you know of, example code that will reproduce this problem? I took a quick look at Eureka, and I'm not sure whether I'll see this error using their example code.

Thanks!

**Comment by apotterri** [comment]
@tokazio I found a [simple example](https://medium.com/javarevisited/how-to-use-spring-cloud-gateway-to-dynamically-discover-microservices-194c0c3869c6) that seemed to reproduce the NPE you were seeing.

v1.17.1 of the agent resolved that problem. I'd be interested to hear whether things work for you now, or if there's still a problem.

Thanks!

**Comment by tokazio** [comment]
Awesome i will check that tomorrow, thanks

**Comment by tokazio** [comment]
There's still an error here with the v1.17.1

```
2023-04-28 14:41:00.091  INFO [prometheus,,] 43031 --- [freshExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://localhost:8102/eureka/}, exception=java.lang.NullPointerException: Parameter specified as non-null is null: method com.appland.shade.okhttp3.HttpUrl$Companion.get, parameter $this$toHttpUrlOrNull stacktrace=com.sun.jersey.api.client.ClientHandlerException: java.lang.NullPointerException: Parameter specified as non-null is null: method com.appland.shade.okhttp3.HttpUrl$Companion.get, parameter $this$toHttpUrlOrNull
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:196)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplications(AbstractJerseyEurekaHttpClient.java:167)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:121)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:80)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1101)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:1014)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1531)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1498)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method com.appland.shade.okhttp3.HttpUrl$Companion.get, parameter $this$toHttpUrlOrNull
	at com.appland.shade.okhttp3.HttpUrl$Companion.get(HttpUrl.kt)
	at com.appland.shade.okhttp3.HttpUrl.get(HttpUrl.kt)
	at com.appland.appmap.process.hooks.HttpClientRequest.execute(HttpClientRequest.java:29)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
	... 30 more
```

**Comment by tokazio** [comment]
We use loadbalanced url like

`lb://servicename/api/endpoint...`

Feign clients are configured with

`@FeignClient(name = "servicename", contextId = "servicenameContextWhatever")`

The main app is annotated with
@LoadBalancerClients(defaultConfiguration = LoadBalancerConfig)

where LoadBalancerConfig is
```
class LoadBalancerConfig {

    @Bean
    ServiceInstanceListSupplier discoveryClientServiceInstanceListSupplier(DiscoveryClient delegate, ConfigurableApplicationContext context) {
        return new DiscoveryClientServiceInstanceListSupplier(delegate,context.environment)
    }

}
```

**Comment by tokazio** [comment]
When debugging, in com.appland.appmap.process.hooks.HttpClientRequest::execute(Event,Object[] args)

HttpUriRequest req = new HttpUriRequest(args[0]);

![image](https://user-images.githubusercontent.com/7676865/235161405-ab056d0b-5832-4ebc-bc2d-62e0cc9d7a43.png)


HttpUrl url = HttpUrl.get(req.getURI()); //Exception here!

![image](https://user-images.githubusercontent.com/7676865/235161605-148a86e3-0786-4877-a672-2a3ff13bf70f.png)

And args is
![image](https://user-images.githubusercontent.com/7676865/235162283-0660342a-3ed3-499f-b86b-ac000d6befde.png)

**Comment by apotterri** [comment]
Thanks for this. There are other cases where we need to use `args[0]`, so I don't think I can just switch them.

What's the full class name of `HttpHost` and `HttpPut` here?

**Comment by tokazio** [comment]
org.apache.http.HttpHost
org.apache.http.client.methods.HttpPut
org.apache.http.client.methods.HttpRequestBase

**Comment by apotterri** [comment]
Great, thanks, that tells me exactly what I need to do to fix this. The fix should be pretty straight-forward.

Because the root cause of this issue is different from the original one, I've opened #177 to track it.

**Comment by tokazio** [comment]
ok nice, waiting for the next version to try ;)
