### ISSUE TITLE
Agent doesn't ignore abstract methods

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-java#192]
When instrumenting a class, the agent doesn't ignore abstract methods. This leads to a failure like:
```
17:51:16.579 [main] ERROR Logger.println: com.appland.appmap.output.v1.NoSourceAvailableException: No code attribute for com.ibm.as400.access.AS400JDBCConnection.nativeSQL(Ljava/lang/String;)Ljava/lang/String;
        at com.appland.appmap.output.v1.Parameters.<init>(Parameters.java:47)
        at com.appland.appmap.output.v1.Event.<init>(Event.java:141)
        at com.appland.appmap.record.EventTemplateRegistry.register(EventTemplateRegistry.java:38)
        at com.appland.appmap.transform.annotations.Hook.prepare(Hook.java:129)
        at com.appland.appmap.transform.ClassFileTransformer.lambda$applyHooks$4(ClassFileTransformer.java:133)
```
which causes instrumentation of the entire class to fail.

**Comment by apotterri** [comment]
Pre-release version that fixes this problem: 

[appmap-1.19.0-SNAPSHOT.jar.gz](https://github.com/getappmap/appmap-java/files/12105613/appmap-1.19.0-SNAPSHOT.jar.gz)
