### ISSUE TITLE
failure when instrumenting  Kotlin app

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-java#214]
When attempting to instrument a function in https://github.com/asm0dey/opdsko, the agent fails with an exception:
```
Exception in thread "main" java.lang.VerifyError: Inconsistent stackmap frames at branch target 184
Exception Details:
  Location:
    io/github/asm0dey/plugins/RoutingKt$routes$1$1.invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object; @159: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @159
    flags: { }
    locals: { 'io/github/asm0dey/plugins/RoutingKt$routes$1$1', 'java/lang/Object', 'io/ktor/util/pipeline/PipelineContext', 'io/ktor/util/pipeline/PipelineContext', integer, 'java/lang/Object' }
    stack: { 'java/lang/Object', 'java/lang/Object' }
  Stackmap Frame:
    bci: @184
    flags: { }
    locals: { 'io/github/asm0dey/plugins/RoutingKt$routes$1$1', 'java/lang/Object', top, top, top, 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: b800 a3b6 00a7 b800 a3b6 00ab 9900 22b8
    0000010: 00b1 1101 1fb6 00b5 2a04 bd00 6d59 032b
    0000020: b800 ba53 b800 c0b8 00a3 b600 c357 0000
    0000030: b800 2b3a 052a b400 2faa 0000 0000 0075
    0000040: 0000 0000 0000 0001 0000 0017 0000 0069
    0000050: 2bb8 0035 2ab4 0039 c000 3b4d 0404 0112
    0000060: 3d04 bb00 3f59 2ab4 000e 2cb7 0042 c000
    0000070: 4407 01b8 004a 572c 4e03 3604 2db6 004d
    0000080: c000 4f12 5101 0101 2ac0 0053 100e 012a
    0000090: 04b5 002f b800 5959 1905 a600 0d19 05a7
    00000a0: 0019 2bb8 0035 2b57 b200 5fa7 000d bb00
    00000b0: 6159 1263 b700 66bf 3a07 b800 a3b6 00ab
    00000c0: 9900 27b8 00b1 1101 1eb6 00c6 2a19 07b8
    00000d0: 00ba 04bd 006d 5903 2bb8 00ba 53b8 00cb
    00000e0: b800 a3b6 00c3 57b8 00a3 b600 ce19 07b0
    00000f0: 3a08 b800 a3b6 00ce 1908 b600 d3c0 006d
    0000100: b03a 09b8 00a3 b600 ab99 0027 b800 b111
    0000110: 011d b600 c62a 1909 c000 d504 bd00 6d59
    0000120: 032b b800 ba53 b800 dab8 00a3 b600 c357
    0000130: b800 a3b6 00ce 1909 bf                 
  Exception Handler Table:
    bci [0, 240] => handler: 240
    bci [0, 257] => handler: 257
  Stackmap Table:
    same_frame(@46)
    full_frame(@80,{Object[#2],Object[#109],Top,Top,Top,Object[#109]},{})
    same_frame_extended(@162)
    full_frame(@167,{Object[#2],Object[#109],Top,Top,Top,Object[#109]},{Object[#109]})
    same_frame(@174)
    full_frame(@184,{Object[#2],Object[#109],Top,Top,Top,Object[#109]},{Object[#109]})
    append_frame(@231,Top,Object[#109])
    full_frame(@240,{Object[#2],Object[#109]},{Object[#208]})
    same_locals_1_stack_item_frame(@257,Object[#213])
    full_frame(@304,{Object[#2],Object[#109],Top,Top,Top,Top,Top,Top,Top,Object[#213]},{})

	at io.github.asm0dey.plugins.RoutingKt$routes$1.invoke(Routing.kt:49)
	at io.github.asm0dey.plugins.RoutingKt$routes$1.invoke(Routing.kt:42)
	at io.ktor.server.routing.Routing$Plugin.install(Routing.kt:139)
	at io.ktor.server.routing.Routing$Plugin.install(Routing.kt:123)
	at io.ktor.server.application.ApplicationPluginKt.install(ApplicationPlugin.kt:100)
	at io.ktor.server.routing.RoutingKt.routing(Routing.kt:163)
	at io.github.asm0dey.plugins.RoutingKt.routes(Routing.kt:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:188)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
	at io.ktor.server.engine.internal.CallableUtilsKt.callFunctionWithInjection(CallableUtils.kt:119)
	at io.ktor.server.engine.internal.CallableUtilsKt.executeModuleFunction(CallableUtils.kt:36)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:332)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$launchModuleByName$1.invoke(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartupFor(ApplicationEngineEnvironmentReloading.kt:356)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.launchModuleByName(ApplicationEngineEnvironmentReloading.kt:331)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.access$launchModuleByName(ApplicationEngineEnvironmentReloading.kt:32)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:312)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading$instantiateAndConfigureApplication$1.invoke(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.avoidingDoubleStartup(ApplicationEngineEnvironmentReloading.kt:338)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:310)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:216)
	at io.ktor.server.netty.EngineMain.main(EngineMain.kt:23)
	at io.github.asm0dey.ApplicationKt.main(Application.kt:146)
```

**Comment by karthick-vinod** [comment]
Facing the same issue.

<details><summary>Exception received</summary>
<p>

org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 3.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy19.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:111)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	... 25 more
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'com.t.invoice.helpers.DataSetupHelper', classLoader = jdk.internal.loader.ClassLoaders$AppClassLoader@368239c8] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	... 32 more
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 1017
Exception Details:
  Location:
    com/t/invoice/helpers/DataSetupHelper.addCredits(Lio/ktor/server/testing/ApplicationTestBuilder;Ljava/math/BigDecimal;Ljava/lang/String;Ljava/time/LocalDate;Ljava/util/Set;Lkotlin/coroutines/Continuation;)Ljava/lang/Object; @996: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @996
    flags: { }
    locals: { 'com/t/invoice/helpers/DataSetupHelper', 'io/ktor/server/testing/ApplicationTestBuilder', 'java/math/BigDecimal', 'java/lang/String', 'java/time/LocalDate', 'java/util/Set', 'kotlin/coroutines/Continuation', '[Z', top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, 'com/google/gson/Gson', 'java/lang/Object', 'com/t/invoice/helpers/DataSetupHelper$addCredits$1', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Stackmap Frame:
    bci: @1017
    flags: { }
    locals: { 'com/t/invoice/helpers/DataSetupHelper', 'io/ktor/server/testing/ApplicationTestBuilder', 'java/math/BigDecimal', 'java/lang/String', 'java/time/LocalDate', 'java/util/Set', 'kotlin/coroutines/Continuation', '[Z', top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, top, 'java/lang/Object', 'com/t/invoice/helpers/DataSetupHelper$addCredits$1', 'java/lang/Object' }
    stack: { 'java/lang/Object', 'java/lang/Object' }
  Bytecode:
    0000000: b807 aeb6 07b1 b807 aeb6 07b4 9900 49b8
    0000010: 07b9 1101 cfb6 07bd 2a10 06bd 0327 5903
    0000020: 2bb8 07cf 5359 042c b807 cf53 5905 2db8
    0000030: 07cf 5359 0619 04b8 07cf 5359 0719 05b8
    0000040: 07cf 5359 0819 06b8 07cf 53b8 07c3 b807
    0000050: aeb6 07c6 5700 0000 1307 8fc0 0791 3a07
    0000060: 1906 c105 809a 000d 1907 1101 4704 54a7
    0000070: 0037 1906 c005 803a 2119 21b4 0583 1305
    0000080: 847e 9a00 0d19 0711 0148 0454 a700 1a19
    0000090: 2159 b405 8313 0584 64b5 0583 1907 1101
    00000a0: 4904 54a7 0016 bb05 8059 2a19 06b7 0587
    00000b0: 3a21 1907 1101 4a04 5419 21b4 058a 3a20
    00000c0: b805 8f19 0711 014b 0454 3a22 1921 b405
    00000d0: 83aa 0000 0000 0316 0000 0000 0000 0002
    00000e0: 0000 001b 0000 0260 0000 02e1 1920 b805
    00000f0: 94bb 0596 5919 0711 014c 0454 b802 3b0a
    0000100: b605 993a 09bb 059b 592d 1305 9d19 0711
    0000110: 014d 0454 1909 1305 9fb8 00a7 1909 0419
    0000120: 0519 042c 1907 1101 4e04 5401 0111 0180
    0000130: 01b7 05a2 b802 7e19 0711 014f 0454 b705
    0000140: a53a 0819 0711 0150 0454 2bb6 05ab 3a0a
    0000150: 1305 ad3a 0b03 360c 190a 3a0d 0336 0e19
    0000160: 0711 0151 0454 190d 3a0f bb05 af59 b705
    0000170: b03a 1019 103a 1103 3612 1907 1101 5204
    0000180: 5419 1119 0bb8 05b6 1911 3a13 0336 1419
    0000190: 0711 0153 0454 1913 c005 b8b2 05bd b605
    00001a0: c0b2 05c5 b605 c9b6 05cc b805 d219 0711
    00001b0: 0154 0454 1913 c005 b8b2 05bd b605 d5b2
    00001c0: 043a b605 d7ba 05da 0000 b805 d219 0711
    00001d0: 0155 0454 1913 3a15 b800 8719 08b6 00b2
    00001e0: 3a16 0336 1719 163a 1819 18c7 0062 1907
    00001f0: 1101 5604 5419 15b2 05df b605 e219 0711
    0000200: 0157 0454 1915 0336 1912 dfb8 05e6 12df
    0000210: b805 e9b8 05ed 3a1a 1907 1101 5804 5419
    0000220: 1ab8 05f3 3a1b 1907 1101 5904 5419 1b12
    0000230: dfb8 03b7 191a b805 f919 0711 015a 0454
    0000240: b605 fd19 0711 015b 0454 a700 8419 18c1
    0000250: 05ff 9900 2819 0711 015c 0454 1915 1916
    0000260: b605 e219 0711 015d 0454 1915 01b6 05fd
    0000270: 1907 1101 5e04 54a7 0057 1915 1916 b605
    0000280: e219 0711 015f 0454 1915 0336 1912 dfb8
    0000290: 05e6 12df b805 e9b8 05ed 3a1a 1907 1101
    00002a0: 6004 5419 1ab8 05f3 3a1b 1907 1101 6104
    00002b0: 5419 1b12 dfb8 03b7 191a b805 f919 0711
    00002c0: 0162 0454 b605 fd19 0711 0163 0454 0000
    00002d0: 0019 103a 1003 361c 1907 1101 6404 5419
    00002e0: 10b2 0604 b606 0ab6 060e 190f 3a1d 0336
    00002f0: 1e19 0711 0165 0454 bb06 1059 1910 191d
    0000300: b706 1319 2119 2104 b505 83b6 0617 5919
    0000310: 22a5 000d 1907 1101 6604 54a7 0030 1907
    0000320: 1101 6704 5419 2219 0711 0168 0454 a700
    0000330: cb03 360c 0336 0e03 361c 0336 1e19 20b8
    0000340: 0594 1920 1907 1101 6904 5400 0000 00c0
    0000350: 0619 3a09 1907 1101 6a04 54b2 061e b606
    0000360: 2419 09b6 0627 0107 01b8 062d 1907 1101
    0000370: 6b04 54b8 0087 3a1f 1909 0119 2104 0119
    0000380: 2119 1fb5 0630 1921 05b5 0583 b806 3659
    0000390: 1922 a500 0d19 0711 016c 0454 a700 2e19
    00003a0: 0711 016d 0454 1922 1907 1101 6e04 54a7
    00003b0: 004a 1921 b406 30c0 00ae 3a1f 1920 b805
    00003c0: 9419 2019 0711 016f 0454 191f 5fc0 00df
    00003d0: 1306 38b6 063c 5913 063e b800 a719 0711
    00003e0: 0170 0454 a700 15bb 0640 5913 0642 b706
    00003f0: 4319 0711 0171 0454 bf3a 24b8 07ae b607
    0000400: b499 004e b807 b911 01d1 b607 c92a 1924
    0000410: b807 cf10 06bd 0327 5903 2bb8 07cf 5359
    0000420: 042c b807 cf53 5905 2db8 07cf 5359 0619
    0000430: 04b8 07cf 5359 0719 05b8 07cf 5359 0819
    0000440: 06b8 07cf 53b8 07d4 b807 aeb6 07c6 57b8
    0000450: 07ae b607 d719 24b0 3a25 b807 aeb6 07d7
    0000460: 1925 b607 dcc0 0327 b03a 26b8 07ae b607
    0000470: b499 004e b807 b911 01d0 b607 c92a 1926
    0000480: c007 de10 06bd 0327 5903 2bb8 07cf 5359
    0000490: 042c b807 cf53 5905 2db8 07cf 5359 0619
    00004a0: 04b8 07cf 5359 0719 05b8 07cf 5359 0819
    00004b0: 06b8 07cf 53b8 07e3 b807 aeb6 07c6 57b8
    00004c0: 07ae b607 d719 26bf                    
  Exception Handler Table:
    bci [0, 1112] => handler: 1112
    bci [0, 1129] => handler: 1129
  Stackmap Table:
    same_frame_extended(@85)
    append_frame(@114,Object[#1937])
    full_frame(@143,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#1408]},{})
    full_frame(@166,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937]},{})
    full_frame(@185,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#1408]},{})
    full_frame(@236,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807]},{})
    full_frame(@589,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Object[#1430],Object[#300],Object[#1645],Object[#223],Integer,Object[#1645],Integer,Object[#1645],Object[#1455],Object[#1455],Integer,Object[#1455],Integer,Object[#1455],Object[#223],Integer,Object[#223],Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807]},{})
    same_frame(@634)
    full_frame(@718,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Object[#1430],Object[#300],Object[#1645],Object[#223],Integer,Object[#1645],Integer,Object[#1645],Object[#1455],Object[#1455],Integer,Object[#1455],Integer,Object[#1455],Object[#223],Integer,Object[#223],Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807]},{})
    full_frame(@798,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Object[#1430],Object[#300],Object[#1645],Object[#223],Integer,Object[#1645],Integer,Object[#1645],Object[#1455],Object[#1455],Integer,Object[#1455],Integer,Object[#1455],Object[#223],Integer,Object[#223],Top,Top,Top,Integer,Object[#1645],Integer,Top,Object[#807],Object[#1408],Object[#807]},{Object[#807]})
    full_frame(@817,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807]},{})
    full_frame(@843,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Integer,Top,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Top,Integer,Top,Object[#807],Object[#1408],Object[#807]},{Object[#807]})
    full_frame(@927,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Object[#1561],Top,Top,Integer,Top,Integer,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Integer,Top,Integer,Object[#174],Object[#807],Object[#1408],Object[#807]},{Object[#807]})
    full_frame(@946,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807]},{})
    full_frame(@970,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#174],Object[#807],Object[#1408],Object[#807]},{Object[#807]})
    full_frame(@999,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807]},{})
    full_frame(@1017,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807]},{Object[#807],Object[#807]})
    full_frame(@1103,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Object[#1937],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#807],Object[#1408],Object[#807],Top,Object[#807]},{Object[#807]})
    full_frame(@1112,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643]},{Object[#2009]})
    same_locals_1_stack_item_frame(@1129,Object[#2014])
    full_frame(@1215,{Object[#2],Object[#1447],Object[#151],Object[#223],Object[#300],Object[#1641],Object[#1643],Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Top,Object[#2014]},{})

	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3192)
	at java.base/java.lang.Class.getMethods(Class.java:1905)
	at org.junit.platform.commons.util.ReflectionUtils.getDefaultMethods(ReflectionUtils.java:1593)
	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:1566)
	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:1407)
	at org.junit.platform.commons.util.ReflectionUtils.isMethodPresent(ReflectionUtils.java:1305)
	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.hasTestOrTestFactoryOrTestTemplateMethods(IsTestClassWithTests.java:50)
	at org.junit.jupiter.engine.discovery.predicates.IsTestClassWithTests.test(IsTestClassWithTests.java:46)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:67)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:135)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:126)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:92)
	... 37 more

</p>
</details>

**Comment by kgilpin** [comment]
Thanks for reporting this. Watch this issue for Kotlin support, at this time only Java is supported.
