### ISSUE TITLE
Appmap generated file name too long

### ISSUE THREAD

**Issue by sergio91pt** [getappmap/appmap-java#75]
I tested on an existent Kotlin codebase and some tests started failing because the generated filename is too long. This is in part because the use of long descriptions in test function names is encouraged.

Running on MAC, I get the following:
```sh
$ getconf PATH_MAX /
1024
$ getconf NAME_MAX /
255
```

Perhaps we could truncate the file name when it approaches the limit.
An idea to then avoid filename clashes could be to include a md5 hash of the intend filename, when it would take more than 255 characters.

Stacktrace from v1.0.4:
```
com.appland.appmap.record.ActiveSessionException: failed to start recording session:
<full path here>appmap.json (File name too long)

        at com.appland.appmap.record.RecordingSessionFileStream.start(RecordingSessionFileStream.java:64)
        at com.appland.appmap.record.Recorder.setActiveSession(Recorder.java:44)
        at com.appland.appmap.record.Recorder.start(Recorder.java:87)
        at com.appland.appmap.process.hooks.ToggleRecord.startRecording(ToggleRecord.java:203)
        at com.appland.appmap.process.hooks.ToggleRecord.junitJupiter(ToggleRecord.java:246)
```

**Comment by kgilpin** [comment]
Thanks for the report! @dustinbyrne @apotterri @ptrdvrk this is how we do it in Ruby - https://github.com/applandinc/appmap-ruby/blob/99da607e05af7b02ca0f454b121449aee8fbab2c/lib/appmap/util.rb#L9 - we should check this in the Python client too
